language: cpp

compiler:
- gcc
- clang

sudo: required

dist: xenial

notifications:
  email: false

install:
  - sudo apt-get install libboost-dev libboost-test-dev

script: make test

env:
- CXXFLAGS=-std=c++98
- CXXFLAGS=-std=c++03
- CXXFLAGS=-std=c++11
- CXXFLAGS=-std=c++14
- CXXFLAGS=-std=c++17

matrix:
  exclude: # travis service doesn't have new compilers for these tests.
  - compiler: clang
    env: CXXFLAGS=-std=c++17
